export const beerCategoryColors = {
  Cider: 'khaki',
  'Sour Beer': 'DarkGrey',
  Lagers: 'gold',
  Pilsener: 'NavajoWhite',
  'Wheat Beer': 'wheat',
  'Pale Ales': 'sandybrown',
  'India Pale Ales': 'goldenrod',
  'Anglo-American Ales': 'rosybrown',
  'Hybrid Beer': 'peru',
  'Strong Ales': 'chocolate',
  'Brown Ales': 'saddlebrown',
  'Dark Lager': 'sienna',
  'Belgian Style': 'brown',
  'Belgian-Style Ales': 'maroon',
  Porter: 'dimgray',
  Stout: 'black',
  'Stout and Porter': 'darkslategray',
  Speciality: 'purple',
  'Other Styles': 'coral',
}

export const beerTypes = [
  'Cider',
  'Sour Beer',
  'Lagers',
  'Pilsener',
  'Wheat Beer',
  'Pale Ales',
  'India Pale Ales',
  'Hybrid Beer',
  'Strong Ales',
  'Brown Ales',
  'Dark Lager',
  'Belgian Style',
  'Belgian-Style Ales',
  'Anglo-American Ales',
  'Porter',
  'Stout',
  'Stout and Porter',
  'Speciality',
  'Other Styles',
]

export const orderingTypes = {
  'Name A-Z': '+name',
  'Name Z-A': '-name',
  'Price (Low-High)': '+merchantsellsfound__price',
  'Price (High-Low)': '-merchantsellsfound__price',
  'Rating (High-Low)': '-rating',
  'Rating (Low-High)': '+rating',
}

export const priceToString = (price) => {
  return (price / 100).toLocaleString('en-US', {
    style: 'currency',
    currency: 'USD',
  })
}

export const brewerArray = {
  'B. Effect': 'b-effect',
  'Epic Brewing Company': 'epic-brewing-company',
  'Burkes Brewing Co': 'burkes-brewing-co',
  Weezledog: 'weezledog',
  'Piha Beer': 'piha-beer',
  'Yeastie Boys': 'yeastie-boys',
  'Brew Mountain': 'brew-mountain',
  "Rudi's": 'rudis',
  'Sidewinder Brewery': 'sidewinder-brewery',
  'Manuherekia Brewery': 'manuherekia-brewery',
  '8 Wired': '8-wired',
  'Ground Up': 'ground-up',
  'Arc Brewing': 'arc-brewing',
  'Liberty Brewing': 'liberty-brewing',
  'Garage Project': 'garage-project',
  Parrotdog: 'parrotdog',
  'Sawmill Brewery': 'sawmill-brewery',
  "Fitzpatrick's Brewing": 'fitzpatricks-brewing',
  'Three Sisters Brewery': 'three-sisters-brewery',
  'Baylands Brewery': 'baylands-brewery',
  'Beer Baroness Brewing Company': 'beer-baroness-brewing-company',
  "Peckham's Cider": 'peckhams-cider',
  'Choice Bros Brewing': 'choice-bros-brewing',
  'Behemoth Brewing': 'behemoth-brewing',
  'Panhead Custom Ales': 'panhead-custom-ales',
  'Bach Brewing': 'bach-brewing',
  'Fiasco Brewing Company': 'fiasco-brewing-company',
  "Duncan's Brewing": 'duncans-brewing',
  'Craftwork Brewery': 'craftwork-brewery',
  'Alibi Brewing': 'alibi-brewing',
  "McLeod's Brewery": 'mcleods-brewery',
  'Altitude Brewing': 'altitude-brewing',
  'Outlier Cartel': 'outlier-cartel',
  'Boom Town Brewing': 'boom-town-brewing',
  'Brave Brewing Co': 'brave-brewing-co',
  'Birkenhead Brewing Company': 'birkenhead-brewing-company',
  'Napier Brewing': 'napier-brewing',
  'Chur Brewing Company': 'chur-brewing-company',
  'Deep Creek Brewing': 'deep-creek-brewing',
  'Southpaw Brewing Company': 'southpaw-brewing-company',
  'Wilderness Brewing': 'wilderness-brewing',
  'Mythica Brewing': 'mythica-brewing',
  'Bootleg Brewery': 'bootleg-brewery',
  'Double Vision Brewing': 'double-vision-brewing',
  'Maiden Brewing Company': 'maiden-brewing-company',
  'Mean Doses': 'mean-doses',
  Brewaucracy: 'brewaucracy',
  'Heyday Beer': 'heyday-beer',
  'Brew Union Brewing Company': 'brew-union-brewing-company',
  'Isthmus Brewing Co': 'isthmus-brewing-co',
  'Lumberjack Brewing': 'lumberjack-brewing',
  'Bassline Brewing': 'bassline-brewing',
  'Urbanaut Brewing': 'urbanaut-brewing',
  'Boneface Brewing': 'boneface-brewing',
  'Volstead Brewing Company': 'volstead-brewing-company',
  'Shining Peak Brewing': 'shining-peak-brewing',
  'DB Breweries': 'db-breweries',
  'Tui Brewery': 'tui-brewery',
  'Lion Beer': 'lion-beer',
  "Emerson's Brewing Company": 'emersons-brewing-company',
  'Speights Brewery': 'speights-brewery',
  "Mac's Brewery": 'macs-brewery',
  "Monteith's Brewing": 'monteiths-brewing',
  'Boundary Road Brewery': 'boundary-road-brewery',
  'Nelson Bays Brewery': 'nelson-bays-brewery',
  'Wanaka Beerworks': 'wanaka-beerworks',
  "Mike's Brewery": 'mikes-brewery',
  'West Coast Brewing': 'west-coast-brewing',
  'Waiheke Island Brewery': 'waiheke-island-brewery',
  'Shakespeare Tavern & Brewery': 'shakespeare-tavern-brewery',
  "Galbraith's Brewing Company": 'galbraiths-brewing-company',
  "Harrington's Brewery": 'harringtons-brewery',
  'The Mussel Inn': 'the-mussel-inn',
  'Sunshine Brewery': 'sunshine-brewery',
  'Roosters Brew House': 'roosters-brew-house',
  'Tuatara Brewing Company': 'tuatara-brewing-company',
  'Hawkes Bay Independent Brewery': 'hawkes-bay-independent-brewery',
  'Meenans Wines and Spirits': 'meenans-wines-and-spirits',
  'Moa Brewing Company': 'moa-brewing-company',
  'Brew Moon Brewing Company': 'brew-moon-brewing-company',
  'The Twisted Hop': 'the-twisted-hop',
  'Wigram Brewing Company': 'wigram-brewing-company',
  'Renaissance Brewing': 'renaissance-brewing',
  'Three Boys Brewery': 'three-boys-brewery',
  'Monsoon Brewing': 'monsoon-brewing',
  'Hallertau Brewbar & Restaurant': 'hallertau-brewbar--restaurant',
  'Mata Brewery': 'mata-brewery',
  'Croucher Brewing': 'croucher-brewing',
  'Sprig and Fern Brewery': 'sprig-and-fern-brewery',
  'Townshend Brewery': 'townshend-brewery',
  'Shunters Yard Brewery': 'shunters-yard-brewery',
  'Golden Bear Brewing Company': 'golden-bear-brewing-company',
  'Scotts Brewing': 'scotts-brewing',
  'Valley Brewing Company': 'valley-brewing-company',
  'McCashin Family Brewery': 'mccashin-family-brewery',
  'Valkyrie Brewing': 'valkyrie-brewing',
  'Smokey Thunder': 'smokey-thunder',
  'Raindogs Brewing': 'raindogs-brewing',
  'Moutere Brewing': 'moutere-brewing',
  'Kereru Brewing Company': 'kereru-brewing-company',
  'Ben Middlemiss Brewing Company': 'ben-middlemiss-brewing-company',
  'Massey University Microbrewery': 'massey-university-microbrewery',
  "Dale's Brewing": 'dales-brewing',
  'Funk Estate': 'funk-estate',
  'Good George Brewing': 'good-george-brewing',
  Pomeroys: 'pomeroys',
  'Queenstown Brewers': 'queenstown-brewers',
  'Hophugger Craft Brews': 'hophugger-craft-brews',
  'Eagle Brewing': 'eagle-brewing',
  'Cassels & Sons Brewing Company': 'cassels-sons-brewing-company',
  'Fork Brewcorp': 'fork-brewcorp',
  'Zeelandt Brewery': 'zeelandt-brewery',
  'Black Dog Brewing Company': 'black-dog-brewing-company',
  'Two Thumb Brewing': 'two-thumb-brewing',
  'Mount Brewing Company': 'mount-brewing-company',
  'Riverhead Cottage Brewery': 'riverhead-cottage-brewery',
  'Brothers Beer': 'brothers-beer',
  'North End Brewing': 'north-end-brewing',
  'Crafty Trout Brewing': 'crafty-trout-brewing',
  'Regent 58': 'regent-58',
  'Rocky Knob Brewing': 'rocky-knob-brewing',
  'Hop Federation Brewery': 'hop-federation-brewery',
  'Hot Water Brewing': 'hot-water-brewing',
  'Abbey Brewery': 'abbey-brewery',
  'Totara Brewing Company': 'totara-brewing-company',
  'Lakeman Brewing Company': 'lakeman-brewing-company',
  'Eruption Brewing': 'eruption-brewing',
  'Specs Brewing Company': 'specs-brewing-company',
  'Laughing Bones Brewing Company': 'laughing-bones-brewing-company',
  'King Country Brewing Company': 'king-country-brewing-company',
  'Black Sands Brewing Company': 'black-sands-brewing-company',
  'Bannockburn Brewing': 'bannockburn-brewing',
  'Te Aro Brewing': 'te-aro-brewing',
  'Vulcan Brewers': 'vulcan-brewers',
  'Jabberwocky Brewing Company': 'jabberwocky-brewing-company',
  'Sparks Brewing': 'sparks-brewing',
  'Catlins Brewery': 'catlins-brewery',
  'Victoria Store Brewery': 'victoria-store-brewery',
  'Sweat Shop Brew Kitchen': 'sweat-shop-brew-kitchen',
  'Giant Brewing Company': 'giant-brewing-company',
  'Martinborough Brewery': 'martinborough-brewery',
  "Schipper's Beer Company": 'schippers-beer-company',
  'Three Fat Pigs': 'three-fat-pigs',
  'Kaikoura Brewing Company': 'kaikoura-brewing-company',
  'Horse Box Brewery': 'horse-box-brewery',
  'The Laboratory': 'the-laboratory',
  'The Herbalist': 'the-herbalist',
  'The Brown Beer': 'the-brown-beer',
  'Emporium Brewing': 'emporium-brewing',
  'New New New': 'new-new-new',
  'Seven Brews': 'seven-brews',
  'Colab Brewing': 'colab-brewing',
  'Concept Brewing': 'concept-brewing',
  'Steamer Basin': 'steam-brewing-company',
  'Fuzzy Logic Brewery': 'fuzzy-logic-brewery',
  'Elation Brewing Company': 'elation-brewing-company',
  'Cargo Brewery': 'cargo-brewery',
  'Mash Palace Brewing': 'mash-palace-brewing',
  'Pilot Brewery': 'pilot-brewery',
  'Raglan Brewing Company': 'raglan-brewing-company',
  'Crazy Bay Beer': 'crazy-bay-beer',
  'Ora Craft Brewery': 'ora-craft-brewery',
  'The Theoretical Brewer': 'the-theoretical-brewer',
  'Cell Division': 'cell-division',
  'Sileni Estates Limited': 'sileni-estates-limited',
  'Boogie Van Brewing': 'boogie-van-brewing',
  'Fortune Favours': 'fortune-favours',
  'Manaia Craft Brewers': 'manaia-craft-brewers',
  'Mandrake Brewing': 'mandrake-brewing',
  'Waiheke Brewing Company': 'waiheke-brewing-company',
  'Chaotic Hop Brewing': 'chaotic-hop-brewing',
  'Kakariki Beer': 'kakariki-beer',
  'Blue Fridge Brewery': 'blue-fridge-brewery',
  'The Island': 'the-island',
  'SUP Brewery': 'sup-brewery',
  'Deco City': 'deco-city',
  'Whistling Sisters Beer': 'whistling-sisters-beer',
  'Kainui Brew': 'kainui-brew',
  'The Fermentist': 'the-fermentist',
  'Scotch Fileha': 'scotch-fileha',
  'Tinker Tailor Brewing': 'tinker-tailor-brewing',
  'Ultimate Brew Company': 'ultimate-brew-company',
  'Wayback Brewing': 'wayback-brewing',
  'The Occasional Brewer': 'the-occasional-brewer',
  'Little Owl Brewing': 'little-owl-brewing',
  'Misfit Brewing': 'misfit-brewing',
  'There Be Dragons Brewing Company': 'there-be-dragons-brewing-company',
  'Ruapehu Brewing': 'ruapehu-brewing',
  'Juicehead Beer': 'juicehead-beer',
  'Slab Brewing': 'slab-brewing',
  'Hunter Hills Brewing': 'hunter-hills-brewing',
  'Bad Neighbour Brewing Company': 'bad-neighbour-brewing-company',
  'Woodstock Brewing': 'woodstock-brewing',
  'Golden Mile Brewing': 'golden-mile-brewing',
  'Trinity Hill': 'trinity-hill',
  'Ghost Brewing': 'ghost-brewing',
  'Katipo Brewing': 'katipo-brewing',
  'Crimson Badger Brewing': 'crimson-badger-brewing',
  'Canyon Food & Brew': 'canyon-food-brew',
  'Abandoned Brewery': 'abandoned-brewery',
  'Hop Farm Brewery': 'hop-farm-brewery',
  'Ship Hop Brewing': 'ship-hop-brewing',
  'Noisy Brewing Company': 'noisy-brewing-company',
  'The Workshop Brewery': 'the-workshop-brewery',
  'Little Thief vs Damaged Goods': 'little-thief-vs-damaged-goods',
  'Paynter’s Cider': 'paynters-cider',
  'Ranga Brewery': 'brand-evolution',
  'Brauhaus Frings': 'brauhaus-frings',
  'Kaiser Brothers Brewery': 'brothers-beer',
  'Arrowtown Brewing': 'arrowtown-brewing',
  bStudio: 'bstudio',
  'Catlins True Brew': 'catlins-true-brew',
  'Change Maker': 'change-maker',
  'Coromandel Brewing': 'coromandel-brewing',
  'Derelict Brewing': 'derelict-brewing',
  'Eddyline Brewery': 'eddyline-brewery-new-zealand',
  'Steam Brewing Company': 'steamer-basin',
  'Rhyme And Reason Brewery': 'rhyme-and-reason-brewery',
  'Rhyme & Reason Brewery': 'rhyme-reason-brewery',
}
