// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BeerCard: typeof import('./src/components/BeerCard.vue')['default']
    BeerPage: typeof import('./src/components/BeerPage.vue')['default']
    CardCarousel: typeof import('./src/components/CardCarousel.vue')['default']
    Filter: typeof import('./src/components/Filter.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    MerchantsCard: typeof import('./src/components/MerchantsCard.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
  }
}

export {}
