branch-defaults:
  main:
    environment: beerfinda-env
    group_suffix: null
environment-defaults:
  Beerfinda-env-1:
    branch: null
    repository: null
global:
  application_name: beerfinda3
  branch: null
  default_ec2_keyname: beerfinda-frontend
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
