export const beerCategoryColors = {
    Cider: "khaki",
    "Sour Beer": "DarkGrey",
    Lagers: "gold",
    Pilsener: "NavajoWhite",
    "Wheat Beer": "wheat",
    "Pale Ales": "sandybrown",
    "India Pale Ales": "goldenrod",
    "Anglo-American Ales": "rosybrown",
    "Hybrid Beer": "peru",
    "Strong Ales": "chocolate",
    "Brown Ales": "saddlebrown",
    "Dark Lager": "sienna",
    "Belgian Style": "brown",
    "Belgian-Style Ales": "maroon",
    Porter: "dimgray",
    Stout: "black",
    "Stout and Porter": "darkslategray",
    Speciality: "purple",
    "Other Styles": "coral",
}

export const beer_types = [
    "Cider",
    "Sour Beer",
    "Lagers",
    "Pilsener",
    "Wheat Beer",
    "Pale Ales",
    "India Pale Ales",
    "Hybrid Beer",
    "Strong Ales",
    "Brown Ales",
    "Dark Lager",
    "Belgian Style",
    "Belgian-Style Ales",
    "Anglo-American Ales",
    "Porter",
    "Stout",
    "Stout and Porter",
    "Speciality",
    "Other Styles",
]